using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Trimming", "IL2046:'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.", Scope = "member", Target = "~M:Mikodev.Binary.Creators.Endianness.DetectEndianConverterCreator.GetConverter(Mikodev.Binary.IGeneratorContext,System.Type)~Mikodev.Binary.IConverter")]
[assembly: SuppressMessage("Trimming", "IL2046:'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.", Scope = "member", Target = "~M:Mikodev.Binary.Creators.KeyValuePairConverterCreator.GetConverter(Mikodev.Binary.IGeneratorContext,System.Type)~Mikodev.Binary.IConverter")]
[assembly: SuppressMessage("Trimming", "IL2046:'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.", Scope = "member", Target = "~M:Mikodev.Binary.Creators.LinkedListConverterCreator.GetConverter(Mikodev.Binary.IGeneratorContext,System.Type)~Mikodev.Binary.IConverter")]
[assembly: SuppressMessage("Trimming", "IL2046:'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.", Scope = "member", Target = "~M:Mikodev.Binary.Creators.NullableConverterCreator.GetConverter(Mikodev.Binary.IGeneratorContext,System.Type)~Mikodev.Binary.IConverter")]
[assembly: SuppressMessage("Trimming", "IL2046:'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.", Scope = "member", Target = "~M:Mikodev.Binary.Creators.PriorityQueueConverterCreator.GetConverter(Mikodev.Binary.IGeneratorContext,System.Type)~Mikodev.Binary.IConverter")]
[assembly: SuppressMessage("Trimming", "IL2046:'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.", Scope = "member", Target = "~M:Mikodev.Binary.Creators.ReadOnlySequenceConverterCreator.GetConverter(Mikodev.Binary.IGeneratorContext,System.Type)~Mikodev.Binary.IConverter")]
[assembly: SuppressMessage("Trimming", "IL2046:'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.", Scope = "member", Target = "~M:Mikodev.Binary.Creators.VariableBoundArrayConverterCreator.GetConverter(Mikodev.Binary.IGeneratorContext,System.Type)~Mikodev.Binary.IConverter")]
[assembly: SuppressMessage("Trimming", "IL2046:'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.", Scope = "member", Target = "~M:Mikodev.Binary.Internal.Contexts.Generator.GetConverter(System.Type)~Mikodev.Binary.IConverter")]
[assembly: SuppressMessage("Trimming", "IL2046:'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.", Scope = "member", Target = "~M:Mikodev.Binary.Internal.Contexts.GeneratorContext.GetConverter(System.Type)~Mikodev.Binary.IConverter")]
